baseURL: "https://blog.adrianordonez.com/"
title: Adrian Ordonez
author: Adrian Ordonez
copyright: "© Adrian Ordonez"
theme: archie
enableInlineShortcodes: true
googleAnalytics: UA-178118381-1

params:
  social:
    - name: GitHub
      icon: github
      url: https://github.com/adrianord
    - name: Twitter
      icon: twitter
      url: https://twitter.com/adrianjordonez
    - name: GitLab
      icon: gitlab
      url: https://gitlab.com/adrianord

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about
      weight: 2
    - name: Tags
      url: /tags
      weight: 3


markup:
  goldmark:
    renderer:
      unsafe: true
